server:
  port: 8081
  servlet:
    context-path: /

spring:
  mvc:
    servlet:
      path: /
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  h2:
    console:
      enabled: true
      path: /db/asset_manager
      settings:
        web-allow-others: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./h2/asset_manager;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE
    jdbc-url: jdbc:h2:file:./h2/asset_manager;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE
    username: test
    password: 1234

  jackson:
    locale: ko_KR
    time-zone: Asia/Seoul

hr-manager:
  url: http://localhost:8080
  key: de585859-4425-4898-9cfe-5b743d5cbda9
